# Site settings
title: "Trenima"
description: "Hayatın içinden"
baseurl: ""
url: "http://trenima.space"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "biz"
    url: /biz/
  - title: "twt"
    url: http://twitter.com/hektowin
